# Loan Eligibility Prediction

### import require packages

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Load the Dataset

In [3]:
df = pd.read_csv("Loan_default.csv")

### Perform Exploratory Data Analysis

In [4]:
df.info

<bound method DataFrame.info of             LoanID  Age  Income  LoanAmount  CreditScore  MonthsEmployed  \
0       I38PQUQS96   56   85994       50587          520              80
1       HPSK72WA7R   69   50432      124440          458              15
2       C1OZ6DPJ8Y   46   84208      129188          451              26
3       V2KKSFM3UN   32   31713       44799          743               0
4       EY08JDHTZP   60   20437        9139          633               8
...            ...  ...     ...         ...          ...             ...
255342  8C6S86ESGC   19   37979      210682          541             109
255343  98R4KDHNND   32   51953      189899          511              14
255344  XQK1UUUNGP   56   84820      208294          597              70
255345  JAO28CPL4H   42   85109       60575          809              40
255346  ZTH91CGL0B   62   22418       18481          636             113

        NumCreditLines  InterestRate  LoanTerm  DTIRatio    Education  \
0                    4         15.23        36      0.44   Bachelor's
1                    1          4.81        60      0.68     Master's
2                    3         21.17        24      0.31     Master's
3                    3          7.07        24      0.23  High School
4                    4          6.51        48      0.73   Bachelor's
...                ...           ...       ...       ...          ...
255342               4         14.11        12      0.85   Bachelor's
255343               2         11.55        24      0.21  High School
255344               3          5.29        60      0.50  High School
255345               1         20.90        48      0.44  High School
255346               2          6.73        12      0.48   Bachelor's

       EmploymentType MaritalStatus HasMortgage HasDependents LoanPurpose  \
0           Full-time      Divorced         Yes           Yes       Other
1           Full-time       Married          No            No       Other
2          Unemployed      Divorced         Yes           Yes        Auto
3           Full-time       Married          No            No    Business
4          Unemployed      Divorced          No           Yes        Auto
...               ...           ...         ...           ...         ...
255342      Full-time       Married          No            No       Other
255343      Part-time      Divorced          No            No        Home
255344  Self-employed       Married         Yes           Yes        Auto
255345      Part-time        Single         Yes           Yes       Other
255346     Unemployed      Divorced         Yes            No   Education

       HasCoSigner  Default
0              Yes        0
1              Yes        0
2               No        1
3               No        0
4               No        0
...            ...      ...
255342          No        0
255343          No        1
255344         Yes        0
255345          No        0
255346         Yes        0

[255347 rows x 18 columns]>

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,255347.0,43.498306,14.990258,18.0,31.00,43.00,56.00,69.0
Income,255347.0,82499.304597,38963.013729,15000.0,48825.50,82466.00,116219.00,149999.0
LoanAmount,255347.0,127578.865512,70840.706142,5000.0,66156.00,127556.00,188985.00,249999.0
CreditScore,255347.0,574.264346,158.903867,300.0,437.00,574.00,712.00,849.0
MonthsEmployed,255347.0,59.541976,34.643376,0.0,30.00,60.00,90.00,119.0
NumCreditLines,255347.0,2.501036,1.117018,1.0,2.00,2.00,3.00,4.0
InterestRate,255347.0,13.492773,6.636443,2.0,7.77,13.46,19.25,25.0
LoanTerm,255347.0,36.025894,16.969330,12.0,24.00,36.00,48.00,60.0
DTIRatio,255347.0,0.500212,0.230917,0.1,0.30,0.50,0.70,0.9
Default,255347.0,0.116128,0.320379,0.0,0.00,0.00,0.00,1.0

In [14]:
df.isnull().sum()   # same as df.isna().sum()

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

## Data preprocessing / Data cleansing

In [15]:
df.drop('LoanID',axis= 1, inplace= True)
df.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [16]:
# convort the categorical into numerical 
from sklearn.preprocessing import LabelEncoder

df['Education'] = LabelEncoder().fit_transform(df['Education'])
df['EmploymentType'] = LabelEncoder().fit_transform(df['EmploymentType'])
df['MaritalStatus'] = LabelEncoder().fit_transform(df['MaritalStatus'])
df['HasMortgage'] = LabelEncoder().fit_transform(df['HasMortgage'])
df['HasDependents'] = LabelEncoder().fit_transform(df['HasDependents'])
df['LoanPurpose'] = LabelEncoder().fit_transform(df['LoanPurpose'])
df['HasCoSigner'] = LabelEncoder().fit_transform(df['HasCoSigner'])

In [17]:
df.shape

(255347, 17)

In [18]:
df['Default'].value_counts()

Default
0    225694
1     29653
Name: count, dtype: int64

### Function for Split the data into training and tesint data set

In [19]:
def  Split_Dataset(x, y):
    from sklearn.model_selection import train_test_split

    X_train, x_test, Y_train, y_test = train_test_split(x, y, train_size= 0.7, random_state=12350, stratify=y)
    return X_train, x_test, Y_train, y_test

# models function

In [20]:

class Models:
    def __init__(self ,X_train, Y_train):
        self.X_train = X_train
        self.Y_train = Y_train
        

    # Built the Logistic Regression model
    def model_LG(self):
        from sklearn.linear_model import LogisticRegressionCV
        model_lg = LogisticRegressionCV().fit(self.X_train, self.Y_train)
        return model_lg

    # Built the Naive Bayes 
    def model_NB(self):
        from sklearn.naive_bayes import GaussianNB
        model_nb = GaussianNB().fit(self.X_train, self.Y_train)
        return model_nb

    # Built the KNN model
    def model_KNN(self):
        from sklearn.neighbors import KNeighborsClassifier
        model_knn = KNeighborsClassifier(n_cluster ).fit(self.X_train, self.Y_train)
        return model_knn

    # Built the Support Vector Machine
    def model_SVM(self):
        from sklearn.svm import SVC
        model_svm = SVC(C=3.0).fit(self.X_train, self.Y_train)
        return model_svm
        
    # Built the Decison tree model 
    def model_DT(self):
        from sklearn.tree import DecisionTreeClassifier
        model_dt = DecisionTreeClassifier().fit(self.X_train, self.Y_train)
        return model_dt

    # Built the model for Random forest
    def model_Rand_forest(self):
        from sklearn.ensemble import RandomForestClassifier
        model_rand_forest = RandomForestClassifier().fit(self.X_train, self.Y_train)
        return model_rand_forest

### classification report and Model Evaluation function

In [21]:
class Model_Evaluation_class:
    def __init__(self ,x_test, y_test):
        self.x_test = x_test
        self.y_test = y_test

    def Classification_Report(self, model):
        from sklearn.metrics import classification_report
        return classification_report(self.y_test, model.predict(self.x_test))

    def model_evaluate(self, model, model_name):
        from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score,f1_score
        
        Accuracy = accuracy_score(self.y_test, model.predict(self.x_test))
        Precision = precision_score(self.y_test, model.predict(self.x_test))
        Recall = recall_score(self.y_test, model.predict(self.x_test))
        f1_Score = f1_score(self.y_test, model.predict(self.x_test))
        return model_name,Accuracy,Precision,Recall,f1_Score

# Deal with imbalanced Data

## Balancing data by using under sampling majority class

In [22]:
# separate the class 1, 0 count 
class_0_count, class_1_count = df['Default'].value_counts()

# separate  the class 1, 0 into 2 df
df_class_0 = df[df['Default']==0]
df_class_1 = df[df['Default']==1]

In [23]:
print(df_class_0['Default'].value_counts())
print(df_class_1['Default'].value_counts())

Default
0    225694
Name: count, dtype: int64
Default
1    29653
Name: count, dtype: int64

In [24]:
60000-29653

30347

In [25]:
df_class_0_under = df_class_0.sample(30347)

In [26]:
balance_df_by_under = pd.concat([df_class_1, df_class_0_under],axis= 0)
balance_df_by_under.value_counts()

Age  Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  InterestRate  LoanTerm  DTIRatio  Education  EmploymentType  MaritalStatus  HasMortgage  HasDependents  LoanPurpose  HasCoSigner  Default
69   142700  25379       494          116             3               4.33          24        0.66      1          2               0              1            1              3            0            0          1
     143074  82339       449          20              3               17.39         36        0.58      1          2               1              0            1              4            0            0          1
     143203  71647       604          66              2               21.03         60        0.31      2          1               2              1            1              2            1            0          1
     144083  134113      754          112             2               20.09         36        0.60      1          2               1              0            0              2            0            0          1
     144248  176622      845          40              2               2.16          24        0.21      1          0               1              0            0              0            0            0          1
                                                                                                                                                                                                                  ..
18   15316   158596      414          47              1               12.14         24        0.11      3          0               1              0            0              2            0            0          1
     15452   173029      773          82              3               23.84         24        0.35      2          3               1              0            0              2            0            1          1
             177764      742          15              1               13.24         36        0.27      1          0               1              1            1              2            1            1          1
     15460   180253      394          91              2               22.29         60        0.18      0          1               1              0            0              2            0            1          1
     15506   203816      356          64              2               19.11         36        0.77      2          3               2              0            0              0            1            1          1
Name: count, Length: 60000, dtype: int64

In [27]:
balance_df_by_under.corr()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
Age,1.000000,0.014928,-0.015774,0.003020,0.023195,-0.004666,-0.035309,-0.004447,-0.013260,0.009022,-0.009909,-0.005484,0.006388,0.009656,0.008975,0.014264,-0.258183
Income,0.014928,1.000000,-0.068455,-0.002103,0.006412,-0.000502,-0.016258,-0.001029,0.003434,0.000129,-0.007879,0.000245,0.002447,-0.000705,-0.003401,-0.005090,-0.147201
LoanAmount,-0.015774,-0.068455,1.000000,-0.000566,-0.003298,0.002452,0.009458,-0.004346,0.001662,-0.002527,0.005968,-0.001950,0.002602,0.000276,0.005081,-0.004314,0.135719
CreditScore,0.003020,-0.002103,-0.000566,1.000000,0.005013,-0.001133,-0.006062,0.002481,-0.002253,0.009505,-0.001480,-0.005664,-0.001210,-0.001522,0.005280,0.007566,-0.052136
MonthsEmployed,0.023195,0.006412,-0.003298,0.005013,1.000000,-0.003083,-0.016108,-0.007016,-0.007056,0.004211,-0.004892,0.010048,0.003685,0.004087,-0.000449,0.009582,-0.154903
NumCreditLines,-0.004666,-0.000502,0.002452,-0.001133,-0.003083,1.000000,0.008437,0.000674,0.000969,0.004417,0.000534,0.000290,-0.003977,0.007051,0.002578,0.000901,0.048895
InterestRate,-0.035309,-0.016258,0.009458,-0.006062,-0.016108,0.008437,1.000000,0.006244,0.008942,-0.002196,0.006196,-0.011900,-0.006681,-0.003395,-0.004464,-0.003829,0.207837
LoanTerm,-0.004447,-0.001029,-0.004346,0.002481,-0.007016,0.000674,0.006244,1.000000,-0.000385,-0.005829,0.000951,-0.007176,0.006286,0.004310,0.002102,0.001955,0.003013
DTIRatio,-0.013260,0.003434,0.001662,-0.002253,-0.007056,0.000969,0.008942,-0.000385,1.000000,0.000821,0.002607,0.008090,-0.001818,0.000043,-0.001399,-0.001203,0.041261
Education,0.009022,0.000129,-0.002527,0.009505,0.004211,0.004417,-0.002196,-0.005829,0.000821,1.000000,0.001623,-0.003352,0.002736,-0.004443,-0.008470,0.001267,-0.040080
EmploymentType,-0.009909,-0.007879,0.005968,-0.001480,-0.004892,0.000534,0.006196,0.000951,0.002607,0.001623,1.000000,0.003428,0.000940,-0.004099,-0.005234,-0.001550,0.067090
MaritalStatus,-0.005484,0.000245,-0.001950,-0.005664,0.010048,0.000290,-0.011900,-0.007176,0.008090,-0.003352,0.003428,1.000000,-0.000163,0.003170,0.000326,0.003788,-0.011070
HasMortgage,0.006388,0.002447,0.002602,-0.001210,0.003685,-0.003977,-0.006681,0.006286,-0.001818,0.002736,0.000940,-0.000163,1.000000,-0.000721,-0.003979,-0.000143,-0.039316
HasDependents,0.009656,-0.000705,0.000276,-0.001522,0.004087,0.007051,-0.003395,0.004310,0.000043,-0.004443,-0.004099,0.003170,-0.000721,1.000000,-0.007335,0.005390,-0.053589
LoanPurpose,0.008975,-0.003401,0.005081,0.005280,-0.000449,0.002578,-0.004464,0.002102,-0.001399,-0.008470,-0.005234,0.000326,-0.003979,-0.007335,1.000000,-0.001520,-0.016136
HasCoSigner,0.014264,-0.005090,-0.004314,0.007566,0.009582,0.000901,-0.003829,0.001955,-0.001203,0.001267,-0.001550,0.003788,-0.000143,0.005390,-0.001520,1.000000,-0.059357
Default,-0.258183,-0.147201,0.135719,-0.052136,-0.154903,0.048895,0.207837,0.003013,0.041261,-0.040080,0.067090,-0.011070,-0.039316,-0.053589,-0.016136,-0.059357,1.000000

### Split the data set into x and y

In [28]:
x = balance_df_by_under[['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed',
       'NumCreditLines', 'InterestRate', 'DTIRatio', 'Education',
       'EmploymentType', 'HasMortgage', 'HasDependents',
       'LoanPurpose', 'HasCoSigner']]
print(x.head())
y = balance_df_by_under['Default']
y.head()
balance_df_by_under.value_counts()

    Age  Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
2    46   84208      129188          451              26               3
5    25   90298       90448          720              18               2
8    36   42053       92357          827              83               1
11   28  149227      139759          375              56               3
18   19   40718       78515          319             119               2

    InterestRate  DTIRatio  Education  EmploymentType  HasMortgage  \
2          21.17      0.31          2               3            1
5          22.72      0.10          1               3            1
8          23.94      0.20          0               2            1
11          5.84      0.80          3               0            0
18         14.00      0.17          0               2            1

    HasDependents  LoanPurpose  HasCoSigner
2               1            0            0
5               0            1            1
8               0            2            0
11              0            2            1
18              0            2            0

Age  Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  InterestRate  LoanTerm  DTIRatio  Education  EmploymentType  MaritalStatus  HasMortgage  HasDependents  LoanPurpose  HasCoSigner  Default
69   142700  25379       494          116             3               4.33          24        0.66      1          2               0              1            1              3            0            0          1
     143074  82339       449          20              3               17.39         36        0.58      1          2               1              0            1              4            0            0          1
     143203  71647       604          66              2               21.03         60        0.31      2          1               2              1            1              2            1            0          1
     144083  134113      754          112             2               20.09         36        0.60      1          2               1              0            0              2            0            0          1
     144248  176622      845          40              2               2.16          24        0.21      1          0               1              0            0              0            0            0          1
                                                                                                                                                                                                                  ..
18   15316   158596      414          47              1               12.14         24        0.11      3          0               1              0            0              2            0            0          1
     15452   173029      773          82              3               23.84         24        0.35      2          3               1              0            0              2            0            1          1
             177764      742          15              1               13.24         36        0.27      1          0               1              1            1              2            1            1          1
     15460   180253      394          91              2               22.29         60        0.18      0          1               1              0            0              2            0            1          1
     15506   203816      356          64              2               19.11         36        0.77      2          3               2              0            0              0            1            1          1
Name: count, Length: 60000, dtype: int64

### Split the data into training and testing dataset

In [29]:
X_train, x_test, Y_train, y_test = Split_Dataset(x, y)

### Build multiple model on above dataset

In [30]:
m1 = Models(X_train,Y_train)
models = [(m1.model_LG(),"LogisticRegression",(0,0)),(m1.model_KNN(), "KNeighborsClassifier",(0,1)),
          (m1.model_NB(),"Naive Bayes",(1,0)),(m1.model_SVM(),"Support Vector Machine",(1,1)),
          (m1.model_DT(),"DecisionTreeClassifier",(2,0)),(m1.model_Rand_forest(),"RandomForest",(2,1))]

/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

### Evaluate all models

In [38]:
model_evaluation_obj = Model_Evaluation_class(x_test, y_test)
Results = []
for model,model_name,_ in models:
    Results.append(model_evaluation_obj.model_evaluate(model, model_name))

df1 = pd.DataFrame(Results,columns=['Algorithm','Accuracy', 'Precision', 'Recall', 'F1_Score'])
df1

                Algorithm  Accuracy  Precision    Recall  F1_Score
0      LogisticRegression  0.678500   0.678699  0.663669  0.671100
1    KNeighborsClassifier  0.540389   0.536074  0.520346  0.528093
2             Naive Bayes  0.677000   0.670314  0.681767  0.675992
3  Support Vector Machine  0.586667   0.631550  0.392873  0.484407
4  DecisionTreeClassifier  0.584611   0.580965  0.572280  0.576590
5            RandomForest  0.678500   0.681919  0.655013  0.668196

### Classification report for all models

In [41]:
for model,model_name,_ in models:
    print(f"Classification report for {model_name} is :")
    print(model_evaluation_obj.Classification_Report(model))
    print("-"*80)

Classification report for LogisticRegression is :
              precision    recall  f1-score   support

           0       0.68      0.69      0.69      9104
           1       0.68      0.66      0.67      8896

    accuracy                           0.68     18000
   macro avg       0.68      0.68      0.68     18000
weighted avg       0.68      0.68      0.68     18000

--------------------------------------------------------------------------------
Classification report for KNeighborsClassifier is :
              precision    recall  f1-score   support

           0       0.54      0.56      0.55      9104
           1       0.54      0.52      0.53      8896

    accuracy                           0.54     18000
   macro avg       0.54      0.54      0.54     18000
weighted avg       0.54      0.54      0.54     18000

--------------------------------------------------------------------------------
Classification report for Naive Bayes is :
              precision    recall  f1-score   support

           0       0.68      0.67      0.68      9104
           1       0.67      0.68      0.68      8896

    accuracy                           0.68     18000
   macro avg       0.68      0.68      0.68     18000
weighted avg       0.68      0.68      0.68     18000

--------------------------------------------------------------------------------
Classification report for Support Vector Machine is :
              precision    recall  f1-score   support

           0       0.57      0.78      0.66      9104
           1       0.63      0.39      0.48      8896

    accuracy                           0.59     18000
   macro avg       0.60      0.58      0.57     18000
weighted avg       0.60      0.59      0.57     18000

--------------------------------------------------------------------------------
Classification report for DecisionTreeClassifier is :
              precision    recall  f1-score   support

           0       0.59      0.60      0.59      9104
           1       0.58      0.57      0.58      8896

    accuracy                           0.58     18000
   macro avg       0.58      0.58      0.58     18000
weighted avg       0.58      0.58      0.58     18000

--------------------------------------------------------------------------------
Classification report for RandomForest is :
              precision    recall  f1-score   support

           0       0.68      0.70      0.69      9104
           1       0.68      0.66      0.67      8896

    accuracy                           0.68     18000
   macro avg       0.68      0.68      0.68     18000
weighted avg       0.68      0.68      0.68     18000

--------------------------------------------------------------------------------

## Oversampling

In [30]:
30347 * 2

60694

In [31]:
df_class_1_over = df_class_1.sample(60000,replace= True)
print(df_class_1_over['Default'].value_counts())
df_class_1_over.head()

Default
1    60000
Name: count, dtype: int64

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
156937,23,123379,35979,837,53,2,24.89,36,0.74,2,0,0,0,0,0,1,1
24441,68,94026,216283,566,40,4,14.64,60,0.48,1,2,1,1,0,1,1,1
232897,19,93287,247098,699,4,3,7.03,12,0.29,3,1,1,1,1,3,0,1
39927,30,123912,229758,329,91,3,13.58,36,0.56,3,3,0,0,1,1,0,1
87186,18,100565,41222,452,49,3,19.25,24,0.56,1,3,2,1,1,4,1,1

In [32]:
df_class_0_reduce = df_class_0.sample(60000)
print(df_class_0['Default'].value_counts())

Default
0    225694
Name: count, dtype: int64

In [33]:
balance_df_by_over = pd.concat([df_class_1_over, df_class_0_reduce],axis=0)
print(balance_df_by_over['Default'].value_counts())

Default
1    60000
0    60000
Name: count, dtype: int64

In [34]:
balance_df_by_over.corr()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
Age,1.000000,0.015290,-0.017831,0.007635,0.018684,-0.007842,-0.038763,-0.001962,-0.012206,0.004096,-0.018142,-0.002588,0.001500,0.009628,0.011580,0.006207,-0.264507
Income,0.015290,1.000000,-0.069971,-0.002637,0.006728,-0.000745,-0.013017,0.001943,0.001845,0.001063,-0.006730,-0.000519,-0.001525,0.004596,-0.001832,-0.002685,-0.150010
LoanAmount,-0.017831,-0.069971,1.000000,-0.005082,-0.005336,0.002830,0.005610,-0.003092,-0.000093,-0.003511,0.007376,-0.000506,-0.005879,0.000048,0.001820,-0.001259,0.134094
CreditScore,0.007635,-0.002637,-0.005082,1.000000,0.006182,-0.002822,-0.007322,-0.000621,0.003373,-0.001469,0.000344,-0.004386,-0.002977,-0.002863,0.003220,0.002902,-0.048827
MonthsEmployed,0.018684,0.006728,-0.005336,0.006182,1.000000,-0.000078,-0.015259,-0.002788,-0.002739,0.000625,-0.003941,0.010295,0.002330,0.004598,0.003398,0.006414,-0.150508
NumCreditLines,-0.007842,-0.000745,0.002830,-0.002822,-0.000078,1.000000,0.005294,-0.002463,0.004086,0.000876,-0.000038,0.001077,-0.005711,0.005463,0.006353,0.000957,0.041968
InterestRate,-0.038763,-0.013017,0.005610,-0.007322,-0.015259,0.005294,1.000000,0.008500,0.007167,-0.005294,0.008617,-0.015735,-0.004076,-0.007098,0.002788,-0.007140,0.206832
LoanTerm,-0.001962,0.001943,-0.003092,-0.000621,-0.002788,-0.002463,0.008500,1.000000,0.003457,-0.000100,0.000591,-0.001900,0.003060,0.010131,0.004215,-0.002358,0.001540
DTIRatio,-0.012206,0.001845,-0.000093,0.003373,-0.002739,0.004086,0.007167,0.003457,1.000000,0.000034,0.005441,0.004588,-0.005801,-0.005294,-0.001688,-0.001901,0.032055
Education,0.004096,0.001063,-0.003511,-0.001469,0.000625,0.000876,-0.005294,-0.000100,0.000034,1.000000,0.003999,-0.007356,0.002480,0.001175,-0.007955,0.007201,-0.035991
EmploymentType,-0.018142,-0.006730,0.007376,0.000344,-0.003941,-0.000038,0.008617,0.000591,0.005441,0.003999,1.000000,-0.002542,0.006529,-0.003799,-0.002996,-0.007792,0.062856
MaritalStatus,-0.002588,-0.000519,-0.000506,-0.004386,0.010295,0.001077,-0.015735,-0.001900,0.004588,-0.007356,-0.002542,1.000000,0.005767,0.003227,-0.002314,-0.002386,-0.014758
HasMortgage,0.001500,-0.001525,-0.005879,-0.002977,0.002330,-0.005711,-0.004076,0.003060,-0.005801,0.002480,0.006529,0.005767,1.000000,0.001006,-0.004405,0.001901,-0.035464
HasDependents,0.009628,0.004596,0.000048,-0.002863,0.004598,0.005463,-0.007098,0.010131,-0.005294,0.001175,-0.003799,0.003227,0.001006,1.000000,-0.009551,0.011186,-0.056226
LoanPurpose,0.011580,-0.001832,0.001820,0.003220,0.003398,0.006353,0.002788,0.004215,-0.001688,-0.007955,-0.002996,-0.002314,-0.004405,-0.009551,1.000000,-0.000676,-0.018154
HasCoSigner,0.006207,-0.002685,-0.001259,0.002902,0.006414,0.000957,-0.007140,-0.002358,-0.001901,0.007201,-0.007792,-0.002386,0.001901,0.011186,-0.000676,1.000000,-0.055688
Default,-0.264507,-0.150010,0.134094,-0.048827,-0.150508,0.041968,0.206832,0.001540,0.032055,-0.035991,0.062856,-0.014758,-0.035464,-0.056226,-0.018154,-0.055688,1.000000

### Split the data set into x and y

In [35]:
x = balance_df_by_over[['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed',
       'NumCreditLines', 'InterestRate', 'DTIRatio', 'Education',
       'EmploymentType', 'HasMortgage', 'HasDependents',
       'LoanPurpose', 'HasCoSigner']]
print(x.head())
y = balance_df_by_over['Default']
y.head()
balance_df_by_over.shape

        Age  Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
156937   23  123379       35979          837              53               2
24441    68   94026      216283          566              40               4
232897   19   93287      247098          699               4               3
39927    30  123912      229758          329              91               3
87186    18  100565       41222          452              49               3

        InterestRate  DTIRatio  Education  EmploymentType  HasMortgage  \
156937         24.89      0.74          2               0            0
24441          14.64      0.48          1               2            1
232897          7.03      0.29          3               1            1
39927          13.58      0.56          3               3            0
87186          19.25      0.56          1               3            1

        HasDependents  LoanPurpose  HasCoSigner
156937              0            0            1
24441               0            1            1
232897              1            3            0
39927               1            1            0
87186               1            4            1

(120000, 17)

### Split the data into training and testing dataset

In [36]:
X_train, x_test, Y_train, y_test = Split_Dataset(x, y)

### Build multiple model on above dataset

In [37]:
m2 = Models(X_train,Y_train)
models = [(m2.model_LG(),"LogisticRegression",(0,0)),(m2.model_KNN(), "KNeighborsClassifier",(0,1)),
          (m2.model_NB(),"Naive Bayes",(1,0)),(m2.model_SVM(),"Support Vector Machine",(1,1)),
          (m2.model_DT(),"DecisionTreeClassifier",(2,0)),(m2.model_Rand_forest(),"RandomForest",(2,1))]

/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/sunbeam/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

### Evaluate all models

In [39]:
model_evaluation_obj = Model_Evaluation_class(x_test, y_test)
Results2 = []
for model,model_name,_ in models:
    Results2.append(model_evaluation_obj.model_evaluate(model, model_name))

df2 = pd.DataFrame(Results2,columns=['Algorithm','Accuracy', 'Precision', 'Recall', 'F1_Score'])
df2

                Algorithm  Accuracy  Precision    Recall  F1_Score
0      LogisticRegression  0.671611   0.672032  0.670389  0.671209
1    KNeighborsClassifier  0.626306   0.614783  0.676500  0.644166
2             Naive Bayes  0.669083   0.662537  0.689222  0.675616
3  Support Vector Machine  0.584889   0.629800  0.411889  0.498052
4  DecisionTreeClassifier  0.783000   0.742803  0.865778  0.799590
5            RandomForest  0.850667   0.832701  0.877667  0.854593

### Classification report for all models

In [40]:
for model,model_name,_ in models:
    print(f"Classification report for {model_name} is :")
    print(model_evaluation_obj.Classification_Report(model))
    print("-"*80)

Classification report for LogisticRegression is :
              precision    recall  f1-score   support

           0       0.67      0.67      0.67     18000
           1       0.67      0.67      0.67     18000

    accuracy                           0.67     36000
   macro avg       0.67      0.67      0.67     36000
weighted avg       0.67      0.67      0.67     36000

--------------------------------------------------------------------------------
Classification report for KNeighborsClassifier is :
              precision    recall  f1-score   support

           0       0.64      0.58      0.61     18000
           1       0.61      0.68      0.64     18000

    accuracy                           0.63     36000
   macro avg       0.63      0.63      0.63     36000
weighted avg       0.63      0.63      0.63     36000

--------------------------------------------------------------------------------
Classification report for Naive Bayes is :
              precision    recall  f1-score   support

           0       0.68      0.65      0.66     18000
           1       0.66      0.69      0.68     18000

    accuracy                           0.67     36000
   macro avg       0.67      0.67      0.67     36000
weighted avg       0.67      0.67      0.67     36000

--------------------------------------------------------------------------------
Classification report for Support Vector Machine is :
              precision    recall  f1-score   support

           0       0.56      0.76      0.65     18000
           1       0.63      0.41      0.50     18000

    accuracy                           0.58     36000
   macro avg       0.60      0.58      0.57     36000
weighted avg       0.60      0.58      0.57     36000

--------------------------------------------------------------------------------
Classification report for DecisionTreeClassifier is :
              precision    recall  f1-score   support

           0       0.84      0.70      0.76     18000
           1       0.74      0.87      0.80     18000

    accuracy                           0.78     36000
   macro avg       0.79      0.78      0.78     36000
weighted avg       0.79      0.78      0.78     36000

--------------------------------------------------------------------------------
Classification report for RandomForest is :
              precision    recall  f1-score   support

           0       0.87      0.82      0.85     18000
           1       0.83      0.88      0.85     18000

    accuracy                           0.85     36000
   macro avg       0.85      0.85      0.85     36000
weighted avg       0.85      0.85      0.85     36000

--------------------------------------------------------------------------------